### create user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "hash-test",
  "email": "hash-test@example.com",
  "password": "lbweininweinfoi"
}

### get user by id
GET http://localhost:3000/users/2d62f81f-c324-47f9-b053-2d202af026cc
Content-Type: application/json
