@baseUrl = http://localhost:3000
@contentType = application/json

### create user (signup)
POST {{baseUrl}}/auth/signup
Content-Type: {{contentType}}

{
  "name": "signup-test",
  "email": "signup-test@example.com",
  "password": "lbweininweinfoi"
}

### sign in
POST {{baseUrl}}/auth/signin
Content-Type: {{contentType}}

{
  "email": "hash-test@example.com",
  "password": "lbweininweinfoi"
}


### get user by id
GET {{baseUrl}}/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkNTE0MTFkNC1hOWVjLTRlNDItOWEyMy0xOTU1NTdiN2UwZjUiLCJpYXQiOjE3NjI5ODg0MzEsImV4cCI6MTc2MzU5MzIzMX0.riOgHPAUoJFoHxlzmy8pynd_ELTwrFu7b4XMJgFPrBU
Content-Type: {{contentType}}